import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import styles from '../styles/Home.module.css'
import HomeHeader from './../components/HomeHeader'
import HomeLatestPosts from '../components/HomeLatestPosts'

export default function Home({ posts }) {
  console.log(posts.data[0].attributes.content)
  return (
    <div className={styles.container}>
      <Head>
        <title>HelloBlog!</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <h1>{props.postsRes}</h1> */}
      <HomeHeader />
      <HomeLatestPosts posts={posts} />
    </div>
  )
}

export async function getServerSideProps(context) {
  const postsRes = await axios.get('http://localhost:1337/api/posts/')
  return {
    props: {
      posts: postsRes.data, // will be passed to the page component as props
    },
  }
}
